---
name: 'Prometheus Operator Lint Action'
author: 'Richard Steinbrueck'
description: 'Run po-lint on your yaml files'
inputs:
  path:
    description: 'Path to files within the repo (and nested directories), it is also possible to add multiple paths separated by a comma'
    required: false
    default: './'
  file_extension:
    description: ''
    required: false
    default: '.yaml'
  exclude:
    description: 'should be a substring of the folder path you want to exclude'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'src/Dockerfile'
branding:
  icon: 'terminal'
  color: 'red'
